<TR CLASS="tablerow1">
	<TD CLASS="normalcol" VALIGN="center">
	<FONT SIZE="2" CLASS="normalcol">ICQ</FONT>
	</TD>
	<TD CLASS="normalcol">
	<FONT SIZE="2"><INPUT NAME="newicq" <?php if ($which != 0) echo "VALUE=\"$this->newicq\" "; else echo "VALUE=\"$newicq\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></FONT>
	</TD>
</TR>
<TR CLASS="tablerow2">
	<TD CLASS="normalcol" VALIGN="center">
	<FONT SIZE="2" CLASS="normalcol">AIM</FONT>
	</TD>
	<TD CLASS="normalcol">
	<FONT SIZE="2"><INPUT NAME="newaim" <?php if ($which != 0) echo "VALUE=\"$this->newaim\" "; else echo "VALUE=\"$newaim\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></FONT>
	</TD>
</TR>
<TR CLASS="tablerow1">
	<TD CLASS="normalcol" VALIGN="center">
	<FONT SIZE="2" CLASS="normalcol">YIM</FONT>
	</TD>
	<TD CLASS="normalcol">
	<FONT SIZE="2"><INPUT NAME="newyim" <?php if ($which != 0) echo "VALUE=\"$this->newyim\" "; else echo "VALUE=\"$newyim\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></FONT>
	</TD>
</TR>
<TR CLASS="tablerow2">
	<TD CLASS="normalcol" VALIGN="center">
	<FONT SIZE="2" CLASS="normalcol">MSN</FONT>
	</TD>
	<TD CLASS="normalcol">
	<FONT SIZE="2"><INPUT NAME="newmsn" <?php if ($which != 0) echo "VALUE=\"$this->newmsn\" "; else echo "VALUE=\"$newmsn\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></FONT>
	</TD>
</TR>