		<TR>
			<TD>
			<DIV CLASS="text">ICQ</DIV>
			</TD>
			<TD>
			<DIV CLASS="text"><INPUT NAME="newicq" <?php if ($which != 0) echo "VALUE=\"$this->newicq\" "; else echo "VALUE=\"$newicq\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></DIV>
			</TD>
		</TR>
		<TR>
			<TD>
			<DIV CLASS="text">AIM</DIV>
			</TD>
			<TD>
			<DIV CLASS="text"><INPUT NAME="newaim" <?php if ($which != 0) echo "VALUE=\"$this->newaim\" "; else echo "VALUE=\"$newaim\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></DIV>
			</TD>
		</TR>
		<TR>
			<TD>
			<DIV CLASS="text">YIM</DIV>
			</TD>
			<TD>
			<DIV CLASS="text"><INPUT NAME="newyim" <?php if ($which != 0) echo "VALUE=\"$this->newyim\" "; else echo "VALUE=\"$newyim\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></DIV>
			</TD>
		</TR>
		<TR>
			<TD>
			<DIV CLASS="text">MSN</DIV>
			</TD>
			<TD>
			<DIV CLASS="text"><INPUT NAME="newmsn" <?php if ($which != 0) echo "VALUE=\"$this->newmsn\" "; else echo "VALUE=\"$newmsn\" "; ?>SIZE="<?php echo $this->inputsize; ?>" MAXLENGTH="15"></DIV>
			</TD>
		</TR>