<?php
	$english[] = "Guestbook";							#0
	$english[] = "currently holding";					#1
	$english[] = "entries";								#2
	$english[] = "Show Newest";							#3
	$english[] = "Sign Guestbook";						#4
	$english[] = "Previous Page";						#5
	$english[] = "Next Page";							#6
	$english[] = "Guestbook - New Entry";				#7
	$english[] = "New Entry";							#8
	$english[] = "Name";								#9
	$english[] = "E-Mail";								#10
	$english[] = "Homepage";							#11
	$english[] = "Text";								#12
	$english[] = "Options";								#13
	$english[] = "Preview";								#14
	$english[] = "Emotions";							#15
	$english[] = "Send";								#16
	$english[] = "Reset";								#17
	$english[] = "Back";								#18
	$english[] = "Guestbook - Preview";					#19
	$english[] = "Yout forgot to enter a name!";		#20
	$english[] = "Please check your e-mail address!";	#21
	$english[] = "You forgot to enter a text!";			#22
	$english[] = "Smileys";								#23
	$english[] = "Clear";								#24
	$english[] = "Search";								#25
	$english[] = "Guestbook - Search";					#26
	$english[] = "search next";							#27
	$english[] = "All light coloured entries are searchresults!!!!";	#28
	$english[] = "Can not find anything!";				#29
	$english[] = "Location";				#30
	$english[] = "Help";				#31
	$english[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$german[] = "G&auml;stebuch";										#0
	$german[] = "momentan sind";										#1
	$german[] = "Eintr&auml;ge vorhanden";								#2
	$german[] = "Aktuelle Beitr&auml;ge";								#3
	$german[] = "Neuer Beitrag";										#4
	$german[] = "Vorherige Seite";										#5
	$german[] = "N&auml;chste Seite";									#6
	$german[] = "G&auml;stebuch - Neuer Beitrag";						#7
	$german[] = "Neuer Beitrag";										#8
	$german[] = "Name";													#9
	$german[] = "E-Mail";												#10
	$german[] = "Homepage";												#11
	$german[] = "Text";													#12
	$german[] = "Optionen";												#13
	$german[] = "Vorschau";												#14
	$german[] = "Emotionen";											#15
	$german[] = "Abschicken";											#16
	$german[] = "Zur&uuml;cksetzen";									#17
	$german[] = "Zur&uuml;ck";											#18
	$german[] = "G&auml;stebuch - Vorschau";							#19
	$german[] = "Sie haben vergessen einen Namen einzugeben!";			#20
	$german[] = "Bitte überprüfen Sie Ihre E-Mail Adresse!";	#21
	$german[] = "Sie haben vergessen einen Text einzugeben!";			#22
	$german[] = "Smileys";												#23
	$german[] = "L&ouml;schen";											#24
	$german[] = "Suchen";												#25
	$german[] = "G&aumlstebuch - Suchen";								#26
	$german[] = "weitersuchen";											#27
	$german[] = "Die hell gekennzeichneten Einträge sind Suchergebnisse!";	#28
	$german[] = "Es wurde nichts gefunden!";							#29
	$german[] = "Ort";				#30
	$german[] = "Hilfe";				#31
	$german[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$swedish[] = "G&auml;stbok";									#0
	$swedish[] = "inneh&aring;ller f&ouml;r tillf&auml;llet";		#1
	$swedish[] = "inl&auml;gg";										#2
	$swedish[] = "Visa de nyaste";									#3
	$swedish[] = "Skriv i g&auml;stboken";							#4
	$swedish[] = "F&ouml;reg&aring;ende sida";						#5
	$swedish[] = "N&auml;sta sida";									#6
	$swedish[] = "G&auml;stbok - Nytt inl&auml;gg";					#7
	$swedish[] = "Nytt inl&auml;gg";								#8
	$swedish[] = "Namn";											#9
	$swedish[] = "E-post";											#10
	$swedish[] = "Hemsida";											#11
	$swedish[] = "Text";											#12
	$swedish[] = "Optioner";										#13
	$swedish[] = "F&ouml;rhandsgranska";							#14
	$swedish[] = "Emotikoner";										#15
	$swedish[] = "S&auml;nd";										#16
	$swedish[] = "T&ouml;m alla f&auml;lt";							#17
	$swedish[] = "Tillbaka";										#18
	$swedish[] = "G&auml;stbok - f&ouml;rhandsgranska";				#19
	$swedish[] = "Du gl&ouml;mde skriva ditt namn!";				#20
	$swedish[] = "Var v&auml;nlig kontrollera din e-postadress!";	#21
	$swedish[] = "Du gl&ouml;mde skriva en text!";					#22
	$swedish[] = "Smileyn";											#23
	$swedish[] = "Helt";											#24
	$swedish[] = "Search";											#25
	$swedish[] = "Guestbook - Search";								#26
	$swedish[] = "search next";										#27
	$swedish[] = "All light coloured entries are searchresults!!!!";	#28
	$swedish[] = "Can not find anything!";							#29
	$swedish[] = "Location";				#30
	$swedish[] = "Help";				#31
	$swedish[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$french[] = "Livre d'Or";										#0
	$french[] = "Ce livre contient actuellement...";				#1
	$french[] = "messages";											#2
	$french[] = "Voir le plus Récent";								#3
	$french[] = "Signer le livre d'Or";								#4
	$french[] = "Page Précédente";									#5
	$french[] = "Page Suivante";									#6
	$french[] = "Livre d'Or - Nouveau Message";						#7
	$french[] = "Nouveau Message";									#8
	$french[] = "Nom";												#9
	$french[] = "E-Mail";											#10
	$french[] = "Site personnel";									#11
	$french[] = "Texte";											#12
	$french[] = "Options";											#13
	$french[] = "Pré-visualiser";									#14
	$french[] = "Emoticônes";										#15
	$french[] = "Envoyer";											#16
	$french[] = "Effacer";											#17
	$french[] = "Retour";											#18
	$french[] = "Livre d'Or - Pré-Visualer";						#19
	$french[] = "Vous avez oublié de saisir votre nom!";			#20
	$french[] = "Vérifiez votre adresse de courriel (e-mail)!";		#21
	$french[] = "Vous avez oublié de saisir votre message!";		#22
	$french[] = "Smileys";											#23
	$french[] = "Nettoyer";											#24
	$french[] = "Search";											#25
	$french[] = "Guestbook - Search";								#26
	$french[] = "search next";										#27
	$french[] = "All light coloured entries are searchresults!!!!";	#28
	$french[] = "Can not find anything!";							#29
	$french[] = "Location";				#30
	$french[] = "Help";				#31
	$french[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$italian[] = "Guestbook";							#0
	$italian[] = "Attualmente sono presenti ";					#1
	$italian[] = "messaggi";							#2
	$italian[] = "Mostra i visitatori recenti";					#3
	$italian[] = "Inserisci messaggio";					#4
	$italian[] = "Pagina precedente";							#5
	$italian[] = "Pagina successiva";							#6
	$italian[] = "Guestbook - Nuovo inserimento";		#7
	$italian[] = "Nuovo inserimento";							#8
	$italian[] = "Nome";										#9
	$italian[] = "E-Mail";										#10
	$italian[] = "Homepage";									#11
	$italian[] = "Messaggio";									#12
	$italian[] = "Opzioni";										#13
	$italian[] = "Anteprima";									#14
	$italian[] = "Faccine";										#15
	$italian[] = "Invia";										#16
	$italian[] = "Ripristina";									#17
	$italian[] = "Indietro";									#18
	$italian[] = "Guestbook - Anteprima";				#19
	$italian[] = "Hai dimenticato di inserire un nome!";		#20
	$italian[] = "Controlla il tuo indirizzo e-mail!";			#21
	$italian[] = "Hai dimenticato di inserire un messaggio!";	#22
	$italian[] = "Faccine";										#23
	$italian[] = "Pulisci";										#24
	$italian[] = "Cerca";										#25
	$italian[] = "Guestbook - Cerca";							#26
	$italian[] = "trova successivo";							#27
	$italian[] = "Tutte le righe chiare sono risultati della ricerca!!!";	#28
	$italian[] = "Spiacente, nessun risultato per la tua ricerca!";			#29
	$italian[] = "Località";				#30
	$italian[] = "Help";				#31
	$italian[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";	
		
	$portuguese[] = "livro de mensagens";						#0
	$portuguese[] = "no momento tem";							#1
	$portuguese[] = "entradas";									#2
	$portuguese[] = "Mais novos";								#3
	$portuguese[] = "Deixa um comentario";						#4
	$portuguese[] = "Pagina anterior";							#5
	$portuguese[] = "Proxima pagina";							#6
	$portuguese[] = "Comentarios - Nova Entrada";				#7
	$portuguese[] = "Nova Entrada";								#8
	$portuguese[] = "Nome";										#9
	$portuguese[] = "E-Mail";									#10
	$portuguese[] = "Homepage";									#11
	$portuguese[] = "Texto";									#12
	$portuguese[] = "Opcoes";									#13
	$portuguese[] = "Preview";									#14
	$portuguese[] = "Icones";									#15
	$portuguese[] = "Enviar";									#16
	$portuguese[] = "Reset";									#17
	$portuguese[] = "Voltar";									#18
	$portuguese[] = "Comentarios - Preview";					#19
	$portuguese[] = "Voce esqueceu o seu nome!";				#20
	$portuguese[] = "Por favor, verifica o seu e-mail!";		#21
	$portuguese[] = "Por favor, escreve algo!";					#22
	$portuguese[] = "Smileys";									#23
	$portuguese[] = "Deleta";									#24
	$portuguese[] = "Search";									#25
	$portuguese[] = "Guestbook - Search";						#26
	$portuguese[] = "search next";								#27
	$portuguese[] = "All light coloured entries are searchresults!!!!";	#28
	$portuguese[] = "Can not find anything!";					#29
	$portuguese[] = "Location";				#30
	$portuguese[] = "Help";				#31
	$portuguese[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$dutch[] = "Gastenboek";									#0
	$dutch[] = "er zijn";										#1
	$dutch[] = "berichten";										#2
	$dutch[] = "Nieuwste berichten";							#3
	$dutch[] = "Teken Gastenboek";								#4
	$dutch[] = "Vorige Pagina";									#5
	$dutch[] = "Volgende Pagina";								#6
	$dutch[] = "Gastenboek - Nieuw bericht";					#7
	$dutch[] = "Nieuw Bericht";									#8
	$dutch[] = "Naam";											#9
	$dutch[] = "E-Mail";										#10
	$dutch[] = "Homepage";										#11
	$dutch[] = "Bericht";										#12
	$dutch[] = "Optie's";										#13
	$dutch[] = "Bekijken";										#14
	$dutch[] = "Emoties";										#15
	$dutch[] = "Verstuur";										#16
	$dutch[] = "Herstel";										#17
	$dutch[] = "Terug";											#18
	$dutch[] = "Gastenboek - Bekijken";							#19
	$dutch[] = "Je bent vergeten je naam in te vullen!";		#20
	$dutch[] = "Controleer a.u.b. Uw E-mail adres!";			#21
	$dutch[] = "Je hebt nog geen bericht ingetyped!";			#22
	$dutch[] = "Smilies";										#23
	$dutch[] = "Wissen";										#24
	$dutch[] = "Zoeken";										#25
	$dutch[] = "Gastenboek - Zoeken";							#26
	$dutch[] = "volgende zoekopdracht";							#27
	$dutch[] = "Alle licht gekleurde berichten zijn zoekresultaten!!!";	#28
	$dutch[] = "Geen zoekresultaaten gevonden!";				#29
	$dutch[] = "Location";				#30
	$dutch[] = "Help";				#31
	$dutch[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$spanish[] = "Libro de visitas";						#0
	$spanish[] = "hay";										#1
	$spanish[] = "entradas actualmente";					#2
	$spanish[] = "Las m&aacute;s reciente";					#3
	$spanish[] = "Firmar el libro de visitas";				#4
	$spanish[] = "P&aacute;gina anterior";					#5
	$spanish[] = "P&aacute;gina siguiente";					#6
	$spanish[] = "Comentarios - nueva entrada";				#7
	$spanish[] = "Nueva Entrada";							#8
	$spanish[] = "Nombre";									#9
	$spanish[] = "E-Mail";									#10
	$spanish[] = "P&aacute;gina Personal";					#11
	$spanish[] = "Texto";									#12
	$spanish[] = "Opciones";								#13
	$spanish[] = "Previsualizar";							#14
	$spanish[] = "Iconos";									#15
	$spanish[] = "Enviar";									#16
	$spanish[] = "Volver a empezar";						#17
	$spanish[] = "Volver";									#18
	$spanish[] = "Comentarios - Previsualizar";				#19
	$spanish[] = "Ha olvidado poner su nombre!";			#20
	$spanish[] = "Por favor, &iexcl;verifique su e-mail!";	#21
	$spanish[] = "Por favor, &iexcl;escriba algo!";			#22
	$spanish[] = "Smileys";									#23
	$spanish[] = "Borrar";									#24
	$spanish[] = "Buscar";									#25
	$spanish[] = "Libro de visitas - B&uacute;squeda";		#26
	$spanish[] = "buscar siguiente";						#27
	$spanish[] = "Todas las entradas de color claro son resultados de la b&uacute;squeda!!!!";	#28
	$spanish[] = "No se puede encontrar nada!";				#29
	$spanish[] = "Location";				#30
	$spanish[] = "Help";				#31
  $spanish[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">";
    
	$russian[] = "Ãîñòåâàÿ êíèãà";								#0
	$russian[] = "íà ñåãîäíÿ åñòü";								#1
	$russian[] = "çàïèñåé";										#2
	$russian[] = "Ïîêàçàòü íîâûå";								#3
	$russian[] = "Îñòàâèòü ñîîáùåíèå";							#4
	$russian[] = "Ïğåäûäóùàÿ ñòğàíèöà";							#5
	$russian[] = "Ñëåäóşùàÿ ñòğàíèöà";							#6
	$russian[] = "Ãîñòåâàÿ êíèãà-ââîä ñîîáùåíèÿ";				#7
	$russian[] = "Íîâîå ñîîáùåíèå";								#8
	$russian[] = "Èìÿ";											#9
	$russian[] = "e-mail";										#10
	$russian[] = "Homepage";									#11
	$russian[] = "Òåêñò";										#12
	$russian[] = "Îïöèÿ";										#13
	$russian[] = "Ïğåäâàğèòåëüíûé ïğîñìîòğ";					#14
	$russian[] = "İìîöèè";										#15
	$russian[] = "Îòïğàâèòü";									#16
	$russian[] = "Îáíîâèòü";									#17
	$russian[] = "Íàçàä";										#18
	$russian[] = "Ãîñòåâàÿ êíèãà-ïğåäâàğèòåëüíûé ïğîñìîòğ";		#19
	$russian[] = "Íå ââåäåíî èìÿ...";							#20
	$russian[] = "Ïîæàëóéñòà ïğîâåğüòå e-mail àäğåñ...";		#21
	$russian[] = "Íå ââåäåí òåêñò...";							#22
	$russian[] = "Ñìàëèêè";										#23
	$russian[] = "Î÷èñòèòü";									#24
	$russian[] = "Search";										#25
	$russian[] = "Guestbook - Search";							#26
	$russian[] = "search next";									#27
	$russian[] = "All light coloured entries are searchresults!!!!";	#28
	$russian[] = "Can not find anything!";						#29
	$russian[] = "Location";				#30
	$russian[] = "Help";				#31
	$russian[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1251\">";
	
	$czech[] = "Kniha návštìv";						#0
	$czech[] = "obsahuje";							#1
	$czech[] = "pøíspìšvkù";						#2
	$czech[] = "Zobraz nejnovìjší";					#3
	$czech[] = "Pøidej pøíspìvek";					#4
	$czech[] = "Pøedchozí strana";					#5
	$czech[] = "Následující strana";				#6
	$czech[] = "Kniha návštìv - Novı pøíspìvek";	#7
	$czech[] = "Novı pøíspìvek";					#8
	$czech[] = "Jméno";								#9
	$czech[] = "E-Mail";							#10
	$czech[] = "Domovská stránka";					#11
	$czech[] = "Text";								#12
	$czech[] = "Volby";								#13
	$czech[] = "Náhled";							#14
	$czech[] = "Oblièeje";							#15
	$czech[] = "Odeslat";							#16
	$czech[] = "Smazat";							#17
	$czech[] = "Zpìt";								#18
	$czech[] = "Kniha návštìv - Náhled";			#19
	$czech[] = "Musíte zadat své jméno!";			#20
	$czech[] = "Musíte zadat svùj e-mail!";			#21
	$czech[] = "Musíte zadat nìjakı text!";			#22
	$czech[] = "Smajlíky";							#23
	$czech[] = "Smazat";							#24
	$czech[] = "Search";							#25
	$czech[] = "Guestbook - Search";				#26
	$czech[] = "search next";						#27
	$czech[] = "All light coloured entries are searchresults!!!!";	#28
	$czech[] = "Can not find anything!";			#29
	$czech[] = "Location";				#30
	$czech[] = "Help";				#31
	$czech[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1250\">";
	
	$finnish[] = "Vieraskirja";										#0
	$finnish[] = "sis&auml;lt&auml;&auml;";							#1
	$finnish[] = "viesti&auml;";									#2
	$finnish[] = "N&auml;yt&auml; Uusimmat";						#3
	$finnish[] = "Kirjoita Vieraskirjaan";							#4
	$finnish[] = "Edellinen Sivu";									#5
	$finnish[] = "Seuraava Sivu";									#6
	$finnish[] = "Vieraskirja - Uusi Viesti";						#7
	$finnish[] = "Uusi Viesti";										#8
	$finnish[] = "Nimi";											#9
	$finnish[] = "S&auml;hk&ouml;posti";							#10
	$finnish[] = "Kotisivu";										#11
	$finnish[] = "Teksti";											#12
	$finnish[] = "Optiot";											#13
	$finnish[] = "Esikatsele";										#14
	$finnish[] = "Hymi&ouml;t";										#15
	$finnish[] = "L&auml;het&auml;";								#16
	$finnish[] = "Resetoi";											#17
	$finnish[] = "Takaisin";										#18
	$finnish[] = "Vieraskirja - Esikatsele";						#19
	$finnish[] = "Unohditte kirjoittaa nimenne!";					#20
	$finnish[] = "Tarkistakaa s&auml;hk&ouml;posti osoitteenne!";	#21
	$finnish[] = "Unohdit kirjoittaa palautetta!";					#22
	$finnish[] = "Hymi&ouml;t";										#23
	$finnish[] = "Tyhjenn&auml;";									#24
	$finnish[] = "Search";											#25
	$finnish[] = "Guestbook - Search";								#26
	$finnish[] = "search next";										#27
	$finnish[] = "All light coloured entries are searchresults!!!!";	#28
	$finnish[] = "Can not find anything!";							#29
	$finnish[] = "Location";				#30
	$finnish[] = "Help";				#31
	$finnish[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$chinese[] = "¯d¨¥ªO";								#0
	$chinese[] = "²{¦³¯d¨¥";							#1
	$chinese[] = "«h";									#2
	$chinese[] = "Åã¥Ü³Ì·s¯d¨¥";						#3
	$chinese[] = "¼g¤U¯d¨¥";							#4
	$chinese[] = "¤W¤@­¶";								#5
	$chinese[] = "¤U¤@­¶";								#6
	$chinese[] = "¯d¨¥ªO - ·s¯d¨¥";						#7
	$chinese[] = "·s¯d¨¥";								#8
	$chinese[] = "ºÙ©I";								#9
	$chinese[] = "¹q¤l«H½c";							#10
	$chinese[] = "ºô¯¸­º­¶";							#11
	$chinese[] = "¥»¤å";								#12
	$chinese[] = "¿ï¶µ";								#13
	$chinese[] = "¹wÄıµ²ªG";							#14
	$chinese[] = "¤ß±¡¹Ï®×";							#15
	$chinese[] = "°e¥X";								#16
	$chinese[] = "­«¸m";								#17
	$chinese[] = "ªğ¦^";								#18
	$chinese[] = "¯d¨¥ªO - ¹wÄı";						#19
	$chinese[] = "§A§Ñ°O¿é¤J¦WºÙÅo¡I";					#20
	$chinese[] = "½Ğ½T©w§AªºE-mail¦ì§}®æ¦¡¬O§_¥¿½T¡I";	#21
	$chinese[] = "§A§Ñ°O¿é¤J¥»¤åÅo¡I";					#22
	$chinese[] = "¤ß±¡¹Ï®×";							#23
	$chinese[] = "²M°£";								#24
	$chinese[] = "Search";								#25
	$chinese[] = "Guestbook - Search";					#26
	$chinese[] = "search next";							#27
	$chinese[] = "All light coloured entries are searchresults!!!!";	#28
	$chinese[] = "Can not find anything!";				#29
	$chinese[] = "Location";				#30
	$chinese[] = "Help";				#31
	$chinese[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">";
	
	$danish[] = "G&aelig;stebog";						#0
	$danish[] = "indeholder nu";						#1
	$danish[] = "Indl&aelig;g";							#2
	$danish[] = "Vis sidste side";						#3
	$danish[] = "Skriv i g&aelig;stebog";				#4
	$danish[] = "Forrige side";							#5
	$danish[] = "N&aelig;ste side";						#6
	$danish[] = "G&aelig;stebog - Nyt indl&aelig;g";	#7
	$danish[] = "Nyt Indl&aelig;g";						#8
	$danish[] = "Navn";									#9
	$danish[] = "E-Mail";								#10
	$danish[] = "Hjemmeside";							#11
	$danish[] = "Tekst";								#12
	$danish[] = "Options";								#13
	$danish[] = "Vis inden afsendelse";					#14
	$danish[] = "Smileys";								#15
	$danish[] = "Afsend";								#16
	$danish[] = "Nulstil";								#17
	$danish[] = "Tilbage";								#18
	$danish[] = "G&aelig;stebog - Vis udskrift";		#19
	$danish[] = "Du glemte at skrive dit navn!";		#20
	$danish[] = "Check lige din  e-mail addresse!";		#21
	$danish[] = "Du glemte at skrive en tekst!";		#22
	$danish[] = "Smileys";								#23
	$danish[] = "SletClear";							#24
	$danish[] = "Search";								#25
	$danish[] = "Guestbook - Search";					#26
	$danish[] = "search next";							#27
	$danish[] = "All light coloured entries are searchresults!!!!";	#28
	$danish[] = "Can not find anything!";				#29
	$danish[] = "Location";				#30
	$danish[] = "Help";				#31
	$danish[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=windows-1252\">";
	
	$polish[] = "Ksiêga go¶ci";									#0
	$polish[] = "aktualnie przechowuje";						#1
	$polish[] = "wpisy/ów";										#2
	$polish[] = "Poka¿ najnowsze";								#3
	$polish[] = "Wpisz siê do Ksiêgi go¶ci";					#4
	$polish[] = "Poprzednia strona";							#5
	$polish[] = "Nastêpna strona";								#6
	$polish[] = "Ksiêga go¶ci - Nowy wpis";						#7
	$polish[] = "Nowy wpis";									#8
	$polish[] = "Imiê";											#9
	$polish[] = "E-Mail";										#10
	$polish[] = "WWW";											#11
	$polish[] = "Komentarz";									#12
	$polish[] = "Opcje";										#13
	$polish[] = "Podgl±d";										#14
	$polish[] = "Emocjonki";									#15
	$polish[] = "Wy¶lij";										#16
	$polish[] = "Reset";										#17
	$polish[] = "Wróæ";											#18
	$polish[] = "Ksiêga go¶ci - Podgl±d wpisu";					#19
	$polish[] = "Zapomnia³e¶ wpisaæ imiê!";						#20
	$polish[] = "Sprawd¼ poprawno¶æ adresu e-mail!";			#21
	$polish[] = "Zapomnia³e¶ wpisaæ co¶ w polu komentarza!";	#22
	$polish[] = "U¶mieszki";									#23
	$polish[] = "Wyczy¶æ";										#24
	$polish[] = "Szukaj";										#25
	$polish[] = "Ksiêga go¶ci - Wyszukiwarka";					#26
	$polish[] = "szukaj nastêpnego";							#27
	$polish[] = "Wszystkie pod¶wietlone wpisy s¹ wynikami wyszukiwania!!!";	#28
	$polish[] = "Nie mog³em nic znale¶æ!";						#29
	$polish[] = "Location";				#30
	$polish[] = "Help";				#31
	$polish[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-2\">";

	$slovak[] = "Kniha náv¹tev";					#0
	$slovak[] = "obsahuje";							#1
	$slovak[] = "príspevkov";						#2
	$slovak[] = "Zobraz najnov¹ie"; 				#3
	$slovak[] = "Pridaj príspevok";					#4
	$slovak[] = "Predchádzajúca strana";			#5
	$slovak[] = "Nasledujúca strana";				#6
	$slovak[] = "Kniha náv¹tev - Novı príspevok";	#7
	$slovak[] = "Novı príspevok";					#8
	$slovak[] = "Meno";		    					#9
	$slovak[] = "E-Mail";							#10
	$slovak[] = "Domovská stránka";					#11
	$slovak[] = "Text";								#12
	$slovak[] = "Voµby";							#13
	$slovak[] = "Náhµad";							#14
	$slovak[] = "Tváre";							#15
	$slovak[] = "Odosla»";							#16
	$slovak[] = "Odstráni»";						#17
	$slovak[] = "Spä»";								#18
	$slovak[] = "Kniha náv¹tev - Náhµad";			#19
	$slovak[] = "Musíte zada» svoje meno!";			#20
	$slovak[] = "Musíte zada» svoj e-mail!";		#21
	$slovak[] = "Musíte zada» nejakı text!";		#22
	$slovak[] = "Smajlíci";							#23
	$slovak[] = "Odstráni»";						#24
	$slovak[] = "Search";								#25
	$slovak[] = "Guestbook - Search";					#26
	$slovak[] = "search next";							#27
	$slovak[] = "All light coloured entries are searchresults!!!";	#28
	$slovak[] = "Can not find anything!";				#29
	$slovak[] = "Location";				#30
	$slovak[] = "Help";				#31
	$slovak[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-2\">";
	
	$icelandic[] = "Gestabók";									#0
	$icelandic[] = "Skráğar færslur";						#1
	$icelandic[] = "Færslur";										#2
	$icelandic[] = "Nıjustu færslur";								#3
	$icelandic[] = "Skrifa í gestabók";					#4
	$icelandic[] = "Fyrri síğa";							#5
	$icelandic[] = "Næsta síğa";								#6
	$icelandic[] = "Gestabók - Nı færsla";						#7
	$icelandic[] = "Nı færsla";									#8
	$icelandic[] = "Nafn";											#9
	$icelandic[] = "Netfang";										#10
	$icelandic[] = "Vefsíğa";											#11
	$icelandic[] = "Texti";									#12
	$icelandic[] = "Valmöguleikar";										#13
	$icelandic[] = "Forskoğa";										#14
	$icelandic[] = "Broskallar";									#15
	$icelandic[] = "Senda";										#16
	$icelandic[] = "Hreinsa";										#17
	$icelandic[] = "Til baka";											#18
	$icelandic[] = "Gestabók - Forskoğa";					#19
	$icelandic[] = "Şú gleymdir ağ skrifa inn nafniğ şitt";						#20
	$icelandic[] = "Athugağu hvort netfangiğ şitt sé rétt slegiğ inn!";			#21
	$icelandic[] = "Şú gleymdir ağ skrifa inn texta!";	#22
	$icelandic[] = "Broskallar";									#23
	$icelandic[] = "Eyğa";										#24
	$icelandic[] = "Leit";										#25
	$icelandic[] = "Gestabók - Leit";					#26
	$icelandic[] = "Leita ağ næsta";							#27
	$icelandic[] = "Allar litağar færslur eru niğurstöğur leitarinnar!";	#28
	$icelandic[] = "Ekkert fannst!";						#29
	$icelandic[] = "Location";				#30
	$icelandic[] = "Help";				#31
	$icelandic[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">";
	
	$hungarian[] = "Vendégkönyv";                               #0
	$hungarian[] = "tartalom:";                                  #1
	$hungarian[] = "bejegyzés";                                   #2
	$hungarian[] = "legújabb";                                     #3
	$hungarian[] = "új bejegyzés";                                  #4
	$hungarian[] = "elõzõ oldal";                                    #5
	$hungarian[] = "következõ oldal";                                 #6
	$hungarian[] = "Vendegkönyv - új bejegyzés";                       #7
	$hungarian[] = "Új bejegyzés";                                      #8
	$hungarian[] = "Név";                                                #9
	$hungarian[] = "E-mail";                                              #10
	$hungarian[] = "Honlap";                                               #11
	$hungarian[] = "Szöveg";                                                #12
	$hungarian[] = "Lehetõség";                                              #13
	$hungarian[] = "Elõnézet";                                                #14
	$hungarian[] = "Szmájli";                                                  #15
	$hungarian[] = "Küldés";                                                    #16
	$hungarian[] = "Mégse";                                                     #17
	$hungarian[] = "Vissza";                                                   #18
	$hungarian[] = "Vendégkönyv - elõnézet";                                  #19
	$hungarian[] = "Ellenõrizze a nevét!";                                   #20
	$hungarian[] = "Ellenõrizze az e-mail címét!";                          #21
	$hungarian[] = "Hiányzó szöveg!";                                      #22
	$hungarian[] = "Szmájlik";                                            #23
	$hungarian[] = "Törlés";                                             #24
	$hungarian[] = "keresés";                                           #25
	$hungarian[] = "Vendégkönyv - keresés";                            #26
	$hungarian[] = "következõ keresés";                               #27
	$hungarian[] = "A keresett szó világos mezõben jelenik meg!!!";  #28
	$hungarian[] = "A keresett szó nem található!";                 #29
	$hungarian[] = "Location";				#30
	$hungarian[] = "Help";				#31
	$hungarian[] = "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-2\">";
?>
