<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<HTML>
<HEAD>
	<TITLE>Guestbook - Administration</TITLE>
	<LINK HREF="../guestbook.css" REL="stylesheet" TYPE="text/css">
</HEAD>

<BODY>

<TABLE BORDER="0" ALIGN="center" VALIGN="middle" WIDTH="100%" HEIGHT="100%">
<TR>
	<TD ALIGN="center">
	<FONT SIZE="5" CLASS="attention">Invalid Password!</FONT><P><BR>
	<FONT CLASS="header" SIZE="2">[ <A HREF="admin.php" ONFOCUS="filter:blur()">Back</A> ]</FONT>	
	</TD>
</TR>
</TABLE>

</BODY>
</HTML>